### ISSUE TITLE
Basically done...I think

### ISSUE THREAD

**Issue by anoonan** [jswizards/Homework#3]
Ok, so I misinterpreted you when you were talking about not executing on a secure webpage. Took me a second but I figured it out. So this code technically works but:
1. It's super boring and is way more basic than I originally intended. I'm not quite sure if this is what you meant or had in mind when you were talking about a reduced boilerplate only because I'm not sure if checking the response code is something that is you have to do over and over again. Originally I was thinking about checking the weather id and having it print something about the weather like (It's raining, etc.), is that more along the lines of what you were thinking?
2. Although it technically works, I think there is a bug because this is the response I get and I don't think I should be getting both:

```
The weather has not been updated.
undefined
The weather is up to date. 

```

**Comment by protocolsix** [comment]
1) The goal of this exercise is to achieve something pretty boring. A reusable helper utility that we can call like the example:

``` javascript
var myXhrModule = {
  /* placeholder */
};

myXhrModule.get('http://api.openweathermap.org/data/2.5/weather?id=5391959', function(result, err) {
  console.log('result was: ', result);
});
```

But we can do this for any URL, not just the weather.

``` javascript
myXhrModule.get('ANY_URL', function(result, err) {
  if (err) {
    console.error('err was: ', err);
  } else {
    console.log('result was: ', result);
  }
});
```

So by creating this utility, we "reduce boilerplate" since we don't have to go through the hassle of setting up the XHR object and doing all that boilerplate code each time.

  2) https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange
You're setting the onreadystatechange callback which is called every time `readyState` of the XHR object changes. So in theory this can be called multiple times. For the purposes of this exercise, we only care about when the request succeeds and we call the callback with the result, or with an error if there was an error.

**Comment by anoonan** [comment]
1) Got it. Ok, that's what I thought. I figured it was to be used across URLs and not specific to one URL. 

2)Ahhh ok, ok. That makes more sense.

**Comment by protocolsix** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#xmlhttprequest-readystate might be useful.
